<a href="https://colab.research.google.com/github/prathik002/DataScience-Lab/blob/main/Program_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#1.Basic Array Creation
import numpy as np

#creating array from list
array_from_list = np.array([1,2,3,4,5])
print("Array from list: ",array_from_list)

#creating array with range of values
print(" ")
array_from_range = np.arange(10)
print("Array with range: ",array_from_range)

#creating array of zeros
print(" ")
zeros_array = np.zeros((3,3))
print("Array of Zeros:\n",zeros_array)

#creating array of ones
print(" ")
ones_array = np.ones((2,5))
print("Array of Ones:\n",ones_array)

Array from list:  [1 2 3 4 5]
 
Array with range:  [0 1 2 3 4 5 6 7 8 9]
 
Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
Array of Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
#2.Array Operations

#creating arrays
a = np.array([1,2,3])
b = np.array([4,5,6])

#element-wise addition
add_result = np.add(a,b)
print("Addition: ",add_result)

#element-wise subtraction
print(" ")
sub_result = np.subtract(a,b)
print("Subtraction: ",sub_result)

#element-wise multiplication
print(" ")
mul_result = np.multiply(a,b)
print("Multiplication: ",mul_result)

#element-wise division
print(" ")
div_result = np.divide(a,b)
print("Division: ",div_result)


Addition:  [5 7 9]
 
Subtraction:  [-3 -3 -3]
 
Multiplication:  [ 4 10 18]
 
Division:  [0.25 0.4  0.5 ]


In [23]:
#3.Array Reshaping

#creeating 1D array
array = np.arange(12)
print("Original array: ",array)

#reshaping to 2D(3X4)
print(" ")
reshaped_array = array.reshape(3,4)
print("Reshaped to 3X4:\n",reshaped_array)

#reshaping to 3D(2X3X2)
print(" ")
reshaped_array_3d = array.reshape(2,3,2)
print("Reshaped to 3D(2X3X2):\n",reshaped_array_3d)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
 
Reshaped to 3X4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
Reshaped to 3D(2X3X2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [29]:
#4.Indexing and Slicing

#creating 2D array
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n",array_2d)

#Accessing element at (1,2)
print(" ")
element = array_2d[1,2]
print("Element at (1,2):\n",element)

#slicing subarray(rows 1 to 2,columns 0 to 1)
print(" ")
subarray = array_2d[1:3,0:2]
print("Sliced subarray:\n",subarray)

#Accessing a column(all rows,column 1)
print(" ")
column = array_2d[:, 1]
print("Column 1:\n",column)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 
Element at (1,2):
 6
 
Sliced subarray:
 [[4 5]
 [7 8]]
 
Column 1:
 [2 5 8]


In [39]:
#5.Statistical Operations

#creating an array
array = np.array([1,2,3,4,5,6,7,8,9,10])

#calculating mean
print(" ")
mean = np.mean(array)
print("Mean:",mean)

#calculating median
print(" ")
median = np.median(array)
print("Median:",median)

#calculating standard deviation
print(" ")
sd = np.std(array)
print("Standard Deviation:",sd)

# min and max values
print(" ")
min = np.min(array)
max = np.max(array)
print(f"Minimum value:{min}\nMaximum value:{max}")

 
Mean: 5.5
 
Median: 5.5
 
Standard Deviation: 2.8722813232690143
 
Minimum value:1
Maximum value:10
