<a href="https://colab.research.google.com/github/prathik002/DataScience-Lab/blob/main/Program_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
"""PROGRAM 3: Write a program to display the elements of the matrix X to different powers and
identity matrix of a given matrix .Also create another matrix Y with same dimensions
and display X 2 +2Y"""

import numpy as np;
X = np.array([[1, 2],
[3, 4]])
Y = np.array([[5,6], [7,8]])
print("Matrix X is :\n ",X)
print("")
print("Matrix Y is : \n",Y)
a=np.power(X,2)
print("")
print("X^2=",a)
result = a + 2 * Y
print("")
print("X^2+2*Y is \n ",result)

Matrix X is :
  [[1 2]
 [3 4]]

Matrix Y is : 
 [[5 6]
 [7 8]]

X^2= [[ 1  4]
 [ 9 16]]

X^2+2*Y is 
  [[11 16]
 [23 32]]
